export function listMetrics(): string {
  const metrics = {
    source_sales: [
      "source_sales.net_sales",
      "source_sales.gross_sales",
      "source_sales.discounts",
      "source_sales.returns",
      "source_sales.tax",
      "source_sales.transactions",
      "source_sales.items_sold",
      "source_sales.average_sale",
      "source_sales.average_items_per_transaction",
      "source_sales.cost",
      "source_sales.gross_profit",
      "source_sales.gross_margin",
    ],
    location_sales: [
      "location_sales.net_sales",
      "location_sales.gross_sales",
      "location_sales.discounts",
      "location_sales.returns",
      "location_sales.tax",
      "location_sales.transactions",
      "location_sales.items_sold",
      "location_sales.average_sale",
      "location_sales.average_items_per_transaction",
      "location_sales.cost",
      "location_sales.gross_profit",
      "location_sales.gross_margin",
      "location_sales.sellthrough",
      "location_sales.inventory_turn",
    ],
    beginning_inventory: [
      "beginning_inventory.quantity",
      "beginning_inventory.cost",
      "beginning_inventory.retail",
      "beginning_inventory.items",
      "beginning_inventory.skus",
      "beginning_inventory.styles",
      "beginning_inventory.departments",
      "beginning_inventory.classes",
      "beginning_inventory.subclasses",
      "beginning_inventory.vendors",
      "beginning_inventory.seasons",
      "beginning_inventory.locations",
      "beginning_inventory.below_reorder",
      "beginning_inventory.below_restock",
      "beginning_inventory.overstock",
      "beginning_inventory.out_of_stock",
      "beginning_inventory.average_cost",
      "beginning_inventory.average_retail",
    ],
    ending_inventory: [
      "ending_inventory.quantity",
      "ending_inventory.cost",
      "ending_inventory.retail",
      "ending_inventory.items",
      "ending_inventory.skus",
      "ending_inventory.styles",
      "ending_inventory.departments",
      "ending_inventory.classes",
      "ending_inventory.subclasses",
      "ending_inventory.vendors",
      "ending_inventory.seasons",
      "ending_inventory.locations",
      "ending_inventory.below_reorder",
      "ending_inventory.below_restock",
      "ending_inventory.overstock",
      "ending_inventory.out_of_stock",
      "ending_inventory.average_cost",
      "ending_inventory.average_retail",
    ],
    shipping: [
      "shipping.shipped",
      "shipping.received",
      "shipping.cost",
    ],
    payment: [
      "payment.amount",
      "payment.count",
    ],
  };

  return JSON.stringify(metrics, null, 2);
}
